module.exports = {
  ERR_SBEE_0001: "No verification key provided !",
  ERR_SBEE_0002: "OTP sent email ID doesn't match with entered email ID",
  ERR_SBEE_0003: "OTP sent mobile number doesn't match with entered phone number",
  ERR_SBEE_0004: "Failed! PhoneNumber is already in use!",
  ERR_SBEE_0005: "Mismatch.OTP entered is wrong",
  ERR_SBEE_0006: "OTP already used /expired",
  ERR_SBEE_0007: "Partner already added wtih same phone number",
  ERR_SBEE_0008: "Email required",
  ERR_SBEE_0009: "Phone number required",
  ERR_SBEE_0010: "OTP required",
  ERR_SBEE_0011: "User not found",
  ERR_SBEE_0012: "Email already exists. Please try login.",
  ERR_SBEE_0013: "Failed! Role does not exist.",
  ERR_SBEE_0014: "Error occured.Please try again",
  ERR_SBEE_0015: "Partner not found",
  ERR_SBEE_0016: "Invalid password",
  ERR_SBEE_0017: "Phone number already in use",
  ERR_SBEE_0018: "Selected goal already in use.Cannot be deleted at the moment.",
  ERR_SBEE_0019: "Selected badge already in use.Cannot be deleted at the moment.",
  ERR_SBEE_0020: "De-link badge and item association before deleting item.",
  ERR_SBEE_0997: "Link invalid or expired ",
  ERR_SBEE_0998: "UnAuthorized",
  ERR_SBEE_0999: "Email ID does not exist",
};
